#!/bin/sh
mkdir out
find ./ -name "*.java" > .source
javac -classpath dependencies/testng.jar -sourcepath src/ -d out/ @.source

cp -r ./src/resources ./out/
echo "====================================="
echo "Compiled Sucessfully"
echo "Now use \"./run\" to start Block Age"
echo "====================================="
